# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: db-mysql-service
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-service
  labels:
    app: db-mysql-service
    tier: database
spec:
  replicas: 1
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: db-mysql-service
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: db-mysql-service
        tier: database
    spec:
      containers:
        - image: mysql:5.7
          imagePullPolicy: "IfNotPresent"
          name: db-mysql-service
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secret
                  key :  password

            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  MYSQL_DATABASE
          ports:
            - containerPort: 3306
              #name: mysql
          volumeMounts:        # Mounting volume obtained from Persistent Volume Claim
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mysql-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion : v1
kind : Secret
metadata:
  name : mysql-secret
data:
  username : cm9vdA==
  password : YWRtaW4wMTIz
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: db-mysql-service  # DNS name
  labels:
    app: db-mysql-service
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       # mysql Pod Should contain same labels
    app: db-mysql-service
    tier: database
  #clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: users
  MYSQL_DATABASE_URL: jdbc:mysql://db-mysql-service:3306/users?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false